name: Deploy VitePress site to GitHub Pages
on:
  push:
    branches: [main] # 确保这是您的主分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取你的代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # 3. 安装项目依赖
      - name: Install dependencies
        run: npm install

      # 4. 执行 VitePress 构建 (并设置正确的 base 路径)
      - name: Build
        # 这里的 --base 是一个保险措施，它会覆盖配置文件中的设置
        # 请把 'Your-Repo-Name' 替换成你的仓库名
        run: npm run docs:build -- --base /MachineWJQ6657.github.io/

      # 5. 将构建好的网站部署到 gh-pages 分支
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 确认 VitePress 构建的输出目录是这个
          publish_dir: docs/.vitepress/dist
